# Generated by Django 4.1 on 2022-10-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPApp', '0003_investigations_investigation_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigations',
            name='domain_name',
            field=models.CharField(max_length=40, verbose_name='Nombre del dominio'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='investigation_date',
            field=models.DateField(verbose_name='Fecha de investigación'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='investigation_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link de la investigación'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='investigation_media',
            field=models.FileField(upload_to='Investigaciones', verbose_name='Archivo de la investigación'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='investigation_name',
            field=models.CharField(max_length=40, verbose_name='Nombre de la investigación'),
        ),
        migrations.AlterField(
            model_name='investigations',
            name='investigation_overview',
            field=models.CharField(max_length=500, verbose_name='Resumen de la investigación'),
        ),
    ]
