# Generated by Django 4.1 on 2022-10-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPApp', '0005_alter_investigations_investigation_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigations',
            name='investigation_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link de la investigación'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='tips_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link del Refuerzo'),
        ),
    ]
